"""
Endpoint de Orquestração do Cálculo do Índice de Harmonia Estética (IHE)
Integração com o motor determinístico (Etapa 1) e controle da Cota Freemium (RN02, RF07, RF13)
"""

from typing import Optional, List
from datetime import datetime, timezone
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Header, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.config import settings
from app.models.entities import User, ClothingItem
from app.schemas.dtos import (
    OutfitCalculateRequest,
    OutfitGenerateRequest,
    RecommendedOutfitResponse,
    ClothingItemResponse,
)
from app.engine.ihe_calculator import calculate_ihe, IHERequest, IHEResponse
from app.engine.color_science import LabColor

router = APIRouter()


async def get_optional_user_id(
    user_id: Optional[UUID] = Query(None, description="ID do usuário (query parameter)"),
    x_user_id: Optional[UUID] = Header(None, alias="X-User-ID", description="ID do usuário (header HTTP)")
) -> Optional[UUID]:
    """Retorna o user_id fornecido via query parameter ou header HTTP."""
    return user_id or x_user_id


@router.post("/calculate-ihe", response_model=IHEResponse, status_code=status.HTTP_200_OK)
async def calculate_ihe_endpoint(
    payload: OutfitCalculateRequest,
    current_user_id: Optional[UUID] = Depends(get_optional_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Orquestra o cálculo do IHE invocando a fórmula mestra determinística.
    Aplica controle de cota Freemium diária de 5 combinações por IA (RN02).
    """
    user: Optional[User] = None

    if current_user_id:
        stmt = select(User).where(User.id == current_user_id)
        res = await db.execute(stmt)
        user = res.scalars().first()

        if not user:
            user = User(
                id=current_user_id,
                email=f"user_{current_user_id}@harmonia.app",
                hashed_password="autogenerated_pass",
                is_premium=False,
                items_count=0,
                looks_generated_today=0,
                created_at=datetime.now(timezone.utc)
            )
            db.add(user)
            await db.flush()

        # Validação estrita da Cota Freemium Diária (RN02)
        if not user.is_premium and user.looks_generated_today >= settings.FREEMIUM_MAX_DAILY_LOOKS:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Limite da cota Freemium de combinações diárias atingido (máximo 5 por dia). Faça upgrade para o Premium."
            )

    # 1. Determinar cor representativa no espaço CIE L*a*b*
    garment_color: LabColor
    if payload.direct_garment_color:
        garment_color = payload.direct_garment_color
    elif payload.item_ids and current_user_id:
        stmt_items = select(ClothingItem).where(
            ClothingItem.id.in_(payload.item_ids),
            ClothingItem.user_id == current_user_id
        )
        res_items = await db.execute(stmt_items)
        items = res_items.scalars().all()

        if items:
            avg_l = sum(item.dominant_l for item in items) / len(items)
            avg_a = sum(item.dominant_a for item in items) / len(items)
            avg_b = sum(item.dominant_b for item in items) / len(items)
            garment_color = LabColor(L=avg_l, a=avg_a, b=avg_b)
        else:
            garment_color = LabColor(L=50.0, a=0.0, b=0.0)
    else:
        garment_color = LabColor(L=50.0, a=0.0, b=0.0)

    # 2. Montar estrutura de dados IHERequest para o motor determinístico
    ihe_req = IHERequest(
        garment_color=garment_color,
        user_palette=payload.user_palette,
        user_biotype=payload.user_biotype,
        garment_cuts=payload.garment_cuts,
        garment_formality=payload.garment_formality,
        occasion=payload.occasion,
        temperature_celsius=payload.temperature_celsius,
        is_raining=payload.is_raining,
        garment_thermal_category=payload.garment_thermal_category,
        user_style_vector=payload.user_style_vector,
        look_style_vector=payload.look_style_vector,
    )

    # 3. Processar o IHE compilado e decomposição dos 4 pilares
    ihe_result = calculate_ihe(ihe_req)

    # 4. Incrementar contador diário de looks do usuário se identificado
    if user:
        user.looks_generated_today += 1
        await db.commit()

    return ihe_result


@router.post("/generate-daily", response_model=List[RecommendedOutfitResponse], status_code=status.HTTP_200_OK)
async def generate_daily_outfits(
    payload: OutfitGenerateRequest,
    current_user_id: UUID = Depends(get_optional_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Gera automaticamente combinações completas de looks a partir do acervo do usuário (RF07).
    Varre o inventário ativo, compõe candidatos viáveis e ranqueia pelo IHE determinístico.
    Aplica controle de cota Freemium diária de 5 combinações por IA (RN02).
    """
    if not current_user_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Identificador de usuário (user_id na query ou X-User-ID no header) é obrigatório."
        )

    stmt_user = select(User).where(User.id == current_user_id)
    res_user = await db.execute(stmt_user)
    user = res_user.scalars().first()

    if not user:
        # Criação transparente do usuário de demonstração caso ainda não persista
        user = User(
            id=current_user_id,
            email=f"user_{current_user_id}@harmonia.app",
            hashed_password="autogenerated_pass",
            body_shape="AMPULHETA",
            seasonal_palette="OUTONO_QUENTE",
            style_vector=[0.0] * 512,
            is_premium=False,
            items_count=0,
            looks_generated_today=0,
            created_at=datetime.now(timezone.utc)
        )
        db.add(user)
        await db.flush()

    # Validação estrita da Cota Freemium Diária (RN02)
    if not user.is_premium and user.looks_generated_today >= settings.FREEMIUM_MAX_DAILY_LOOKS:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Limite da cota Freemium de combinações diárias atingido (máximo 5 por dia). Faça upgrade para o Premium."
        )

    # Buscar itens ativos do usuário (RN01 - isolamento estrito)
    stmt_items = select(ClothingItem).where(
        ClothingItem.user_id == current_user_id,
        ClothingItem.is_archived == False
    )
    res_items = await db.execute(stmt_items)
    items = res_items.scalars().all()

    if not items:
        return []

    # Gerar recomendações ranqueadas
    from app.engine.outfit_generator import generate_outfit_recommendations
    recommendations = generate_outfit_recommendations(
        items=list(items),
        user=user,
        occasion=payload.occasion,
        temperature_celsius=payload.temperature_celsius,
        is_raining=payload.is_raining,
        limit=payload.limit,
    )

    # Incrementa cota Freemium diária utilizada
    user.looks_generated_today += 1
    await db.commit()

    # Mapear para DTOs de resposta
    response_list = []
    for rec in recommendations:
        response_list.append(
            RecommendedOutfitResponse(
                items=[ClothingItemResponse.model_validate(it) for it in rec.items],
                ihe_score=rec.ihe_result.ihe_score,
                ihe_percentage=rec.ihe_result.ihe_percentage,
                s_cor=rec.ihe_result.s_cor,
                s_bio=rec.ihe_result.s_bio,
                s_ocasion=rec.ihe_result.s_ocasion,
                s_cos=rec.ihe_result.s_cos,
                is_strongly_recommended=rec.ihe_result.is_strongly_recommended,
                styling_advice=rec.styling_advice,
                occasion=payload.occasion,
            )
        )

    return response_list

