"""
Endpoint de Orquestração do Cálculo do Índice de Harmonia Estética (IHE)
Integração com o motor determinístico (Etapa 1) e controle da Cota Freemium (RN02, RF07, RF13)
"""

from typing import Optional
from datetime import datetime, timezone
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Header, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.core.database import get_db
from app.core.config import settings
from app.models.entities import User, ClothingItem
from app.schemas.dtos import OutfitCalculateRequest
from app.engine.ihe_calculator import calculate_ihe, IHERequest, IHEResponse
from app.engine.color_science import LabColor

router = APIRouter()


async def get_optional_user_id(
    user_id: Optional[UUID] = Query(None, description="ID do usuário (query parameter)"),
    x_user_id: Optional[UUID] = Header(None, alias="X-User-ID", description="ID do usuário (header HTTP)")
) -> Optional[UUID]:
    """Retorna o user_id fornecido via query parameter ou header HTTP."""
    return user_id or x_user_id


@router.post("/calculate-ihe", response_model=IHEResponse, status_code=status.HTTP_200_OK)
async def calculate_ihe_endpoint(
    payload: OutfitCalculateRequest,
    current_user_id: Optional[UUID] = Depends(get_optional_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Orquestra o cálculo do IHE invocando a fórmula mestra determinística.
    Aplica controle de cota Freemium diária de 5 combinações por IA (RN02).
    """
    user: Optional[User] = None

    if current_user_id:
        stmt = select(User).where(User.id == current_user_id)
        res = await db.execute(stmt)
        user = res.scalars().first()

        if not user:
            user = User(
                id=current_user_id,
                email=f"user_{current_user_id}@harmonia.app",
                hashed_password="autogenerated_pass",
                is_premium=False,
                items_count=0,
                looks_generated_today=0,
                created_at=datetime.now(timezone.utc)
            )
            db.add(user)
            await db.flush()

        # Validação estrita da Cota Freemium Diária (RN02)
        if not user.is_premium and user.looks_generated_today >= settings.FREEMIUM_MAX_DAILY_LOOKS:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Limite da cota Freemium de combinações diárias atingido (máximo 5 por dia). Faça upgrade para o Premium."
            )

    # 1. Determinar cor representativa no espaço CIE L*a*b*
    garment_color: LabColor
    if payload.direct_garment_color:
        garment_color = payload.direct_garment_color
    elif payload.item_ids and current_user_id:
        stmt_items = select(ClothingItem).where(
            ClothingItem.id.in_(payload.item_ids),
            ClothingItem.user_id == current_user_id
        )
        res_items = await db.execute(stmt_items)
        items = res_items.scalars().all()

        if items:
            avg_l = sum(item.dominant_l for item in items) / len(items)
            avg_a = sum(item.dominant_a for item in items) / len(items)
            avg_b = sum(item.dominant_b for item in items) / len(items)
            garment_color = LabColor(L=avg_l, a=avg_a, b=avg_b)
        else:
            garment_color = LabColor(L=50.0, a=0.0, b=0.0)
    else:
        garment_color = LabColor(L=50.0, a=0.0, b=0.0)

    # 2. Montar estrutura de dados IHERequest para o motor determinístico
    ihe_req = IHERequest(
        garment_color=garment_color,
        user_palette=payload.user_palette,
        user_biotype=payload.user_biotype,
        garment_cuts=payload.garment_cuts,
        garment_formality=payload.garment_formality,
        occasion=payload.occasion,
        temperature_celsius=payload.temperature_celsius,
        is_raining=payload.is_raining,
        garment_thermal_category=payload.garment_thermal_category,
        user_style_vector=payload.user_style_vector,
        look_style_vector=payload.look_style_vector,
    )

    # 3. Processar o IHE compilado e decomposição dos 4 pilares
    ihe_result = calculate_ihe(ihe_req)

    # 4. Incrementar contador diário de looks do usuário se identificado
    if user:
        user.looks_generated_today += 1
        await db.commit()

    return ihe_result
