"""
CRUD de Peças do Acervo Virtual com Isolamento Multi-Tenant (RN01) e Cota Freemium (RN02, RF06)
"""

from typing import List, Optional
from datetime import datetime, timezone
from uuid import UUID
import uuid

from fastapi import APIRouter, Depends, HTTPException, Query, Header, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, asc, desc

from app.core.database import get_db
from app.core.config import settings
from app.models.entities import User, ClothingItem
from app.schemas.dtos import (
    ClothingItemCreate,
    ClothingItemResponse,
)

router = APIRouter()


async def get_current_user_id(
    user_id: Optional[UUID] = Query(None, description="ID do usuário (query parameter)"),
    x_user_id: Optional[UUID] = Header(None, alias="X-User-ID", description="ID do usuário (header HTTP)")
) -> UUID:
    """Extrai e valida o user_id recebido via query string ou header HTTP."""
    target_id = user_id or x_user_id
    if not target_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Identificador de usuário (user_id na query ou X-User-ID no header) é obrigatório."
        )
    return target_id


@router.get("/items", response_model=List[ClothingItemResponse], status_code=status.HTTP_200_OK)
async def list_clothing_items(
    current_user_id: UUID = Depends(get_current_user_id),
    category: Optional[str] = Query(None, description="Filtrar por categoria"),
    min_formality: Optional[float] = Query(None, ge=0.0, le=1.0, description="Formalidade mínima"),
    max_formality: Optional[float] = Query(None, ge=0.0, le=1.0, description="Formalidade máxima"),
    cut_type: Optional[str] = Query(None, description="Filtrar por corte/modelagem"),
    include_archived: bool = Query(False, description="Incluir peças arquivadas"),
    sort_by: str = Query("created_at", description="Campo para ordenação"),
    order: str = Query("desc", description="Direção da ordenação (asc ou desc)"),
    db: AsyncSession = Depends(get_db),
):
    """
    Lista peças do guarda-roupa do usuário logado (RN01) com suporte a filtros multicritérios (RF06).
    """
    stmt = select(ClothingItem).where(ClothingItem.user_id == current_user_id)

    if not include_archived:
        stmt = stmt.where(ClothingItem.is_archived == False)

    if category:
        stmt = stmt.where(ClothingItem.category == category)

    if min_formality is not None:
        stmt = stmt.where(ClothingItem.formality_score >= min_formality)

    if max_formality is not None:
        stmt = stmt.where(ClothingItem.formality_score <= max_formality)

    if cut_type:
        stmt = stmt.where(ClothingItem.cut_type == cut_type)

    if sort_by == "formality_score":
        col = ClothingItem.formality_score
    elif sort_by == "category":
        col = ClothingItem.category
    else:
        col = ClothingItem.created_at

    if order.lower() == "asc":
        stmt = stmt.order_by(asc(col))
    else:
        stmt = stmt.order_by(desc(col))

    result = await db.execute(stmt)
    items = result.scalars().all()

    return [ClothingItemResponse.model_validate(item) for item in items]


@router.post("/items", response_model=ClothingItemResponse, status_code=status.HTTP_201_CREATED)
async def create_clothing_item(
    item_in: ClothingItemCreate,
    current_user_id: UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Cadastra uma nova peça de vestuário no acervo virtual do usuário.
    Enforça a Cota Freemium (RN02 - máximo 30 peças para não-premium) e atualiza items_count.
    """
    stmt = select(User).where(User.id == current_user_id)
    result = await db.execute(stmt)
    user = result.scalars().first()

    if not user:
        user = User(
            id=current_user_id,
            email=f"user_{current_user_id}@harmonia.app",
            hashed_password="autogenerated_pass",
            is_premium=False,
            items_count=0,
            looks_generated_today=0,
            created_at=datetime.now(timezone.utc)
        )
        db.add(user)
        await db.flush()

    # Validação estrita da Cota Freemium (RN02)
    if not user.is_premium and user.items_count >= settings.FREEMIUM_MAX_CLOTHING_ITEMS:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Limite da cota Freemium atingido (máximo 30 peças). Faça upgrade para o Premium."
        )

    new_item = ClothingItem(
        id=uuid.uuid4(),
        user_id=current_user_id,
        category=item_in.category,
        subcategory=item_in.subcategory,
        image_url=item_in.image_url,
        dominant_l=item_in.dominant_l,
        dominant_a=item_in.dominant_a,
        dominant_b=item_in.dominant_b,
        formality_score=item_in.formality_score,
        cut_type=item_in.cut_type,
        style_embedding=item_in.style_embedding,
        is_archived=False,
        created_at=datetime.now(timezone.utc)
    )

    user.items_count += 1

    db.add(new_item)
    await db.commit()
    await db.refresh(new_item)

    return ClothingItemResponse.model_validate(new_item)


@router.delete("/items/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_clothing_item(
    item_id: UUID,
    current_user_id: UUID = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Exclui uma peça garantindo validação de posse e isolamento Multi-Tenant estrito (RN01).
    """
    stmt = select(ClothingItem).where(ClothingItem.id == item_id)
    result = await db.execute(stmt)
    item = result.scalars().first()

    if not item:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Peça de vestuário não encontrada."
        )

    # Validação de posse para isolamento Multi-Tenant (RN01)
    if item.user_id != current_user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Acesso negado. Esta peça não pertence ao usuário informado."
        )

    # Decrementa o contador de peças do usuário
    user_stmt = select(User).where(User.id == current_user_id)
    user_res = await db.execute(user_stmt)
    user = user_res.scalars().first()
    if user and user.items_count > 0:
        user.items_count -= 1

    await db.delete(item)
    await db.commit()
    return None
